server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3307/appdb
        username: appuser
        password: pass
        driver-class-name: com.mysql.cj.jdbc.Driver